# マップ原点の設定
origin_pose: 34.648955532,135.3864642795,47.4248278253 #万博下見のデータ
origin_quat: 0.0,0.0,0.0,1.0

# expo_crowd_msgs::Crowd => expo_crowd_msgs::CrowdFix
sub_crowd_topic: "crowd"
pub_crowd_fix_topic: "crowd_fix"

# expo_msgs::Area => expo_fix_msgs::AreaFix
sub_area_topic: "data_topic"
pub_area_fix_topic: "data_topic_fix"

# expo_msgs::Person => expo_fix_msgs::PersonFix
sub_person_topic: "person"
pub_person_fix_topic: "person_fix"

# maigo(geometry_msgs::Vector3) => sensor_msgs::NavSatFix
sub_maigo_topic: "maigo"
pub_maigo_fix_topic: "maigo_fix"

# otoshimono(geometry_msgs::Vector3) => sensor_msgs::NavSatFix
sub_otosimono_topic: "otosimono"
pub_otosimono_fix_topic: "otosimono_fix"

# nav_msgs::Odometry => expo_fix_msgs::FixWithOrientation
sub_odom_topic1: "hokuyo_lio/sync_odom"
pub_fix_topic1: "odom_fix"

# geometry_msgs::PoseStamped => sensor_msgs::NavSatFix
sub_pose_topic2: "pose"
pub_fix_topic2: "fix/from_pose"

# geometry_msgs::PoseWithCovarianceStamped => sensor_msgs::NavSatFix
sub_posecov_topic3: "posecov"
pub_fix_topic3: "fix/from_posecov"

