fix2xyz_in:
  ros__parameters:
    # マップ原点の設定
    origin_pose: 34.64871869933758,135.3863518424095,40.21804520297207
    origin_quat_inv: 0.13171921765866876,-0.1267485924485938,0.25479114565859995,0.9502464655232625

    # sensor_msgs::NavSatFix => nav_msgs::Odometry
    sub_fix_topic0: "fix"
    pub_odom_topic0: "odometry/fix"

    # expo_fix_msgs::FixWithOrientation => nav_msgs::Odometry
    sub_fix_topic1: "fix1"
    pub_odom_topic1: "odometry/from_fix1"

    # sensor_msgs::NavSatFix => geometry_msgs::PoseStamped
    sub_fix_topic2: "expo_waypoint"
    pub_pose_topic2: "goal"

    # sensor_msgs::NavSatFix => geometry_msgs::PoseWithCovarianceStamped
    sub_fix_topic3: "expo_initpose"
    pub_posecov_topic3: "initialpose"

    # その他のオプション
    rot_cov: 1000000000.0
    make_angle_from_movement: true
