map_file: "/home/takahashi/catkin_ws/src/expo_wizurg/map/ATC_area_1.pcd"
initial_pose: "-3.0 -1.5 0.0 0.0 0.0 0.906307787 0.422618"
frames_accumulate: 1
min_registration_interval: 0
asynchronous_registration: true