# localization_params.yaml (修正案)
simple_fastlio_localization:
  ros__parameters:
    # パラメータ設定
    #map_file: "/home/hokuyo/colcon_ws/src/hokuyo_navigation2/map/toyonaka.pcd"                                 # 地図ファイルへのパス
    #initial_pose: "0.0872598054993432 -0.27655916619551135 -0.08039461249999391 0.0027502847 -0.0015631212 -0.9623909263 0.271649954" # 初期姿勢 (x, y, z, qx, qy, qz, qw) - スペース区切りの文字列に修正
    frames_accumulate: 4                         # マッチングのために蓄積するフレーム数
    min_registration_distance: 0.0               # 登録のための最小距離
    asynchronous_registration: true              # 非同期登録を有効にするか
    publish_2d_pose: true                       # /map -> /odom 変換として2D姿勢を公開するか
    visualize_registration_result: true         # 色分けして登録結果を視覚化するか
    enable_sound: true                          # 登録結果の音声通知を有効にするか

    # トピックリマッピングのデフォルト値 (ROS2 launchファイルで上書き可能)
    odom_topic: "/hokuyo_lio/lidar_odom"
    cloud_odom_topic: "/hokuyo_lio/aligned_scan_points"
    pose_topic: "/estimated_pose"
    map_topic: "/map_cloud"