switch_odom_tf:
  ros__parameters:
    sub_topic_name: "odometry/switch_on_map"
    pub_topic_name: "dummy"
    frame_id: "map"
    child_frame_id: "base_link"
    tf_en: true
    odom_en: false
    use_init_R: false
    init_num: 5
    R_arr: [ 1.0, 0.0, 0.0, 
            0.0, 1.0, 0.0, 
            0.0, 0.0, 1.0]
    position_arr: [0.0,0.0,0.0]
