xyz2fix_in:
  ros__parameters:
    # マップ原点の設定
    origin_pose: 34.64871869933758,135.3863518424095,40.21804520297207
    origin_quat_inv: 0.13171921765866876,-0.1267485924485938,0.25479114565859995,0.9502464655232625

    # nav_msgs::Odometry => expo_fix_msgs::FixWithOrientation
    sub_odom_topic1: "hokuyo_lio/sync_odom"
    pub_fix_topic1: "odom_fix"

    # geometry_msgs::PoseStamped => sensor_msgs::NavSatFix
    sub_pose_topic2: "pose"
    pub_fix_topic2: "fix/from_pose"

    # geometry_msgs::PoseWithCovarianceStamped => sensor_msgs::NavSatFix
    sub_posecov_topic3: "posecov"
    pub_fix_topic3: "fix/from_posecov"

